### ISSUE TITLE
Feedback.  Alexa. While it recognizes the fan and the dimmer, it is unable to recognize the switch

### ISSUE THREAD

**Issue by riteshchipbucket** [Luligu/matterbridge-example-dynamic-platform#1]
"I have developed a plugin using this example, but I want to implement feedback so that the device ID can be updated automatically. This will ensure that any changes are reflected on the mobile app in real-time. Could you provide me with the perfect function to achieve this feedback mechanism?"

**Comment by Luligu** [comment]
Hi,
I would be more than happy to collaborate if you want...

**Comment by riteshchipbucket** [comment]
Thanks for your response. I have completed the feedback functionality, so I have closed this issue. I have coded a plugin for switches, fans and dimmers that are working perfectly with Apple Home, Google Home and Home Assistant. However, I am facing a problem with Alexa. While it recognizes the fan and the dimmer, it is unable to recognize the switch.

**Comment by Luligu** [comment]
Hi,
this is a well know issue of Alexa:
https://github.com/Luligu/matterbridge?tab=readme-ov-file#alexa

Just use Outlet or Light for On/Off device.

What plugin are you coding ?

The current version of this plugin now show almost all device types, so really easy to test different controllers.
